#基本设置，包括随机种子、GPU 选择、调试模式、实验名称等
basic:
  seed: 12345
  GPU: 0 #选择的 GPU 编号
  debug: False
  id: 'unnamed'
  mode: train
  search: False #不启用搜索模式.搜索模式，通常用于进行超参数搜索或实验搜索
  amp: 'Native' #自动混合精度（Automatic Mixed Precision，AMP）的模式。深度学习训练技术，加速模型训练并减少内存使用。使用原生的AMP模式。

experiment:
#  name: 'RandomKTrainTestSplit'
  name: 'OrganoidTrainTestSplit'
  random_state: 12345
  run_fold: 1 #运行次数
  Filter: True
  radom_sample: True



data:
  #数据集目录
  img_dir: '/home/hryang/Singleorgans/'
  data_dir: '/home/xlzhu/Work2_SCVPrediction/Results/Test/work14_CTC/s4_CalculateMetrics/singlecell'
  #data_dir: 'G:\AnfangBiology\Results\S1analysis\s4_CalculateMetrics\singlecell'
#  data_dir: 'G:\AnfangBiology\ctcSample'
  #数据框目录(dataframe)
  df_dir: '/home/xlzhu/Work2_SCVPrediction/Results/Test/work14_CTC/s4_CalculateMetrics'
  #df_dir: 'G:\AnfangBiology\Results\S1analysis\s4_CalculateMetrics'
  train_img_type: 'cell'


model:
  name: 'AutoEncoder'
#  name: 'AE_residual'
  params:
    encoded_space_dim: 100 #编码空间维度



train:
  #dir: '/home/xlzhu/heying/CTCs/Result/CAE/'
#  dir: '/home/xlzhu/heying/CTCs/Result/ResAE/'
    #dir: '/home/hying/CTCs/CAE/Results/S2ConvolutionAutoEncoder/' #训练结果的保存目录
  dir: '/home/hryang/code/newWhole/result/ResAE/'
  batch_size: 16
  num_epochs: 50


eval:
  batch_size: 1


loss:
  name: 'mse' #均方误差（Mean Squared Error）损失函数
  params:
    flag: True


optimizer:
  name: 'Adam'
  step: 1
  params:
    lr: 0.001 #权重更新的步长或大小
    weight_decay: 0 #权重衰减（weight decay）是一种正则化项,帮助防止模型过拟合

#定义学习率调度器（learning rate scheduler）,控制了训练过程中学习率的变化
scheduler:
  name: 'CosineAnnealingLR' #使用余弦退火学习率调度器
  warm_up: True #学习率热身（warm-up）,表示在训练开始阶段学习率将逐渐升高，然后再按照余弦退火策略降低。
                #学习率热身有助于在训练初期更快地接近最优解，然后再通过余弦退火策略细调学习率
  params:
    factor: 0.1 #学习率的缩放因子
    patience: 10 #余弦退火中的 "patience" 参数，用于控制学习率的更新周期
                 #设置为 10，这意味着学习率将在每个 10 个周期之后进行更新。


transform:
  name: None
  num_preprocessor: 10
#  size: 256
  size: 96
